// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXMrKb89fiz3xruprVdf_A0hJ3G5_a1Os',
    appId: '1:281313840400:web:ef6af8e3a49240716ba995',
    messagingSenderId: '281313840400',
    projectId: 'ritchat-93086',
    authDomain: 'ritchat-93086.firebaseapp.com',
    storageBucket: 'ritchat-93086.firebasestorage.app',
    measurementId: 'G-4042TMT5DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuYJ96r8z3rK8IZZEgGns5_q_AD3l0qw',
    appId: '1:281313840400:android:8815269748f3c6536ba995',
    messagingSenderId: '281313840400',
    projectId: 'ritchat-93086',
    storageBucket: 'ritchat-93086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefB0C6qlIgbsWH4OFNsSIo5qLoPfPdpQ',
    appId: '1:281313840400:ios:7bb76d4228fc2d8a6ba995',
    messagingSenderId: '281313840400',
    projectId: 'ritchat-93086',
    storageBucket: 'ritchat-93086.firebasestorage.app',
    iosBundleId: 'com.example.ritChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBefB0C6qlIgbsWH4OFNsSIo5qLoPfPdpQ',
    appId: '1:281313840400:ios:7bb76d4228fc2d8a6ba995',
    messagingSenderId: '281313840400',
    projectId: 'ritchat-93086',
    storageBucket: 'ritchat-93086.firebasestorage.app',
    iosBundleId: 'com.example.ritChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXMrKb89fiz3xruprVdf_A0hJ3G5_a1Os',
    appId: '1:281313840400:web:9d0b8ae5d00617d86ba995',
    messagingSenderId: '281313840400',
    projectId: 'ritchat-93086',
    authDomain: 'ritchat-93086.firebaseapp.com',
    storageBucket: 'ritchat-93086.firebasestorage.app',
    measurementId: 'G-HBVVX4YBVT',
  );

}