name: Build iOS (Unsigned)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"   # ✅ matches Dart 3.9.0
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Force iOS 15 platform
        run: |
          cd ios
          # Prepend platform line to Podfile (always ensures iOS 15)
          echo 'platform :ios, "15.0"' | cat - Podfile > temp && mv temp Podfile
          head -n 5 Podfile   # ✅ print first lines for debug

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod repo update
          pod install

      - name: Build iOS archive (no codesign)
        run: |
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $PWD/build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export unsigned IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Runner.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist <(cat <<EOF
          {
            "method": "development",
            "signingStyle": "manual",
            "stripSwiftSymbols": true,
            "compileBitcode": false
          }
EOF
)

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: build/ipa/Runner.ipa
